// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv_store.proto

/*
Package objectserver is a generated protocol buffer package.

It is generated from these files:
	kv_store.proto

It has these top-level messages:
	KVAsyncJob
	ListAsyncJobsMsg
	ListAsyncJobsReply
	SaveAsyncJobMsg
	SaveAsyncJobReply
	CleanAsyncJobMsg
	CleanAsyncJobReply
*/
package objectserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KVAsyncJob struct {
	Method    string            `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Headers   map[string]string `protobuf:"bytes,2,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Account   string            `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	Container string            `protobuf:"bytes,4,opt,name=container" json:"container,omitempty"`
	Object    string            `protobuf:"bytes,5,opt,name=object" json:"object,omitempty"`
	Device    string            `protobuf:"bytes,6,opt,name=device" json:"device,omitempty"`
	Policy    int32             `protobuf:"varint,7,opt,name=policy" json:"policy,omitempty"`
}

func (m *KVAsyncJob) Reset()                    { *m = KVAsyncJob{} }
func (m *KVAsyncJob) String() string            { return proto.CompactTextString(m) }
func (*KVAsyncJob) ProtoMessage()               {}
func (*KVAsyncJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KVAsyncJob) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *KVAsyncJob) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *KVAsyncJob) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *KVAsyncJob) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *KVAsyncJob) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *KVAsyncJob) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *KVAsyncJob) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

type ListAsyncJobsMsg struct {
	Device     string      `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	Policy     int32       `protobuf:"varint,2,opt,name=policy" json:"policy,omitempty"`
	Pagination int32       `protobuf:"varint,3,opt,name=pagination" json:"pagination,omitempty"`
	Position   *KVAsyncJob `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
}

func (m *ListAsyncJobsMsg) Reset()                    { *m = ListAsyncJobsMsg{} }
func (m *ListAsyncJobsMsg) String() string            { return proto.CompactTextString(m) }
func (*ListAsyncJobsMsg) ProtoMessage()               {}
func (*ListAsyncJobsMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListAsyncJobsMsg) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *ListAsyncJobsMsg) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *ListAsyncJobsMsg) GetPagination() int32 {
	if m != nil {
		return m.Pagination
	}
	return 0
}

func (m *ListAsyncJobsMsg) GetPosition() *KVAsyncJob {
	if m != nil {
		return m.Position
	}
	return nil
}

type ListAsyncJobsReply struct {
	Jobs []*KVAsyncJob `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *ListAsyncJobsReply) Reset()                    { *m = ListAsyncJobsReply{} }
func (m *ListAsyncJobsReply) String() string            { return proto.CompactTextString(m) }
func (*ListAsyncJobsReply) ProtoMessage()               {}
func (*ListAsyncJobsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListAsyncJobsReply) GetJobs() []*KVAsyncJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type SaveAsyncJobMsg struct {
	Job *KVAsyncJob `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *SaveAsyncJobMsg) Reset()                    { *m = SaveAsyncJobMsg{} }
func (m *SaveAsyncJobMsg) String() string            { return proto.CompactTextString(m) }
func (*SaveAsyncJobMsg) ProtoMessage()               {}
func (*SaveAsyncJobMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SaveAsyncJobMsg) GetJob() *KVAsyncJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type SaveAsyncJobReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *SaveAsyncJobReply) Reset()                    { *m = SaveAsyncJobReply{} }
func (m *SaveAsyncJobReply) String() string            { return proto.CompactTextString(m) }
func (*SaveAsyncJobReply) ProtoMessage()               {}
func (*SaveAsyncJobReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveAsyncJobReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CleanAsyncJobMsg struct {
	Job *KVAsyncJob `protobuf:"bytes,4,opt,name=job" json:"job,omitempty"`
}

func (m *CleanAsyncJobMsg) Reset()                    { *m = CleanAsyncJobMsg{} }
func (m *CleanAsyncJobMsg) String() string            { return proto.CompactTextString(m) }
func (*CleanAsyncJobMsg) ProtoMessage()               {}
func (*CleanAsyncJobMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CleanAsyncJobMsg) GetJob() *KVAsyncJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type CleanAsyncJobReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *CleanAsyncJobReply) Reset()                    { *m = CleanAsyncJobReply{} }
func (m *CleanAsyncJobReply) String() string            { return proto.CompactTextString(m) }
func (*CleanAsyncJobReply) ProtoMessage()               {}
func (*CleanAsyncJobReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CleanAsyncJobReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*KVAsyncJob)(nil), "objectserver.KVAsyncJob")
	proto.RegisterType((*ListAsyncJobsMsg)(nil), "objectserver.ListAsyncJobsMsg")
	proto.RegisterType((*ListAsyncJobsReply)(nil), "objectserver.ListAsyncJobsReply")
	proto.RegisterType((*SaveAsyncJobMsg)(nil), "objectserver.SaveAsyncJobMsg")
	proto.RegisterType((*SaveAsyncJobReply)(nil), "objectserver.SaveAsyncJobReply")
	proto.RegisterType((*CleanAsyncJobMsg)(nil), "objectserver.CleanAsyncJobMsg")
	proto.RegisterType((*CleanAsyncJobReply)(nil), "objectserver.CleanAsyncJobReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KVStore service

type KVStoreClient interface {
	SaveAsyncJob(ctx context.Context, in *SaveAsyncJobMsg, opts ...grpc.CallOption) (*SaveAsyncJobReply, error)
	ListAsyncJobs(ctx context.Context, in *ListAsyncJobsMsg, opts ...grpc.CallOption) (*ListAsyncJobsReply, error)
	CleanAsyncJob(ctx context.Context, in *CleanAsyncJobMsg, opts ...grpc.CallOption) (*CleanAsyncJobReply, error)
}

type kVStoreClient struct {
	cc *grpc.ClientConn
}

func NewKVStoreClient(cc *grpc.ClientConn) KVStoreClient {
	return &kVStoreClient{cc}
}

func (c *kVStoreClient) SaveAsyncJob(ctx context.Context, in *SaveAsyncJobMsg, opts ...grpc.CallOption) (*SaveAsyncJobReply, error) {
	out := new(SaveAsyncJobReply)
	err := grpc.Invoke(ctx, "/objectserver.KVStore/SaveAsyncJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ListAsyncJobs(ctx context.Context, in *ListAsyncJobsMsg, opts ...grpc.CallOption) (*ListAsyncJobsReply, error) {
	out := new(ListAsyncJobsReply)
	err := grpc.Invoke(ctx, "/objectserver.KVStore/ListAsyncJobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) CleanAsyncJob(ctx context.Context, in *CleanAsyncJobMsg, opts ...grpc.CallOption) (*CleanAsyncJobReply, error) {
	out := new(CleanAsyncJobReply)
	err := grpc.Invoke(ctx, "/objectserver.KVStore/CleanAsyncJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KVStore service

type KVStoreServer interface {
	SaveAsyncJob(context.Context, *SaveAsyncJobMsg) (*SaveAsyncJobReply, error)
	ListAsyncJobs(context.Context, *ListAsyncJobsMsg) (*ListAsyncJobsReply, error)
	CleanAsyncJob(context.Context, *CleanAsyncJobMsg) (*CleanAsyncJobReply, error)
}

func RegisterKVStoreServer(s *grpc.Server, srv KVStoreServer) {
	s.RegisterService(&_KVStore_serviceDesc, srv)
}

func _KVStore_SaveAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAsyncJobMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).SaveAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectserver.KVStore/SaveAsyncJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).SaveAsyncJob(ctx, req.(*SaveAsyncJobMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ListAsyncJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAsyncJobsMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ListAsyncJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectserver.KVStore/ListAsyncJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ListAsyncJobs(ctx, req.(*ListAsyncJobsMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_CleanAsyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanAsyncJobMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).CleanAsyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objectserver.KVStore/CleanAsyncJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).CleanAsyncJob(ctx, req.(*CleanAsyncJobMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "objectserver.KVStore",
	HandlerType: (*KVStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveAsyncJob",
			Handler:    _KVStore_SaveAsyncJob_Handler,
		},
		{
			MethodName: "ListAsyncJobs",
			Handler:    _KVStore_ListAsyncJobs_Handler,
		},
		{
			MethodName: "CleanAsyncJob",
			Handler:    _KVStore_CleanAsyncJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv_store.proto",
}

func init() { proto.RegisterFile("kv_store.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0xa4, 0x1f, 0xd9, 0xbd, 0x5b, 0xb5, 0x5e, 0x44, 0x86, 0xa2, 0x6b, 0x09, 0x08, 0x45,
	0x34, 0x0f, 0xd5, 0x07, 0x59, 0x50, 0x51, 0x11, 0xc4, 0x55, 0x90, 0x14, 0xf6, 0x55, 0x92, 0xe9,
	0x65, 0x37, 0xdd, 0x9a, 0x09, 0x99, 0x69, 0x20, 0x3f, 0xc0, 0xff, 0xe0, 0xab, 0xff, 0x54, 0x66,
	0xa6, 0x71, 0x27, 0xd1, 0xd6, 0x7d, 0xeb, 0x39, 0xf7, 0xde, 0x73, 0xcf, 0x3d, 0xcd, 0xc0, 0xed,
	0xab, 0xea, 0x9b, 0x54, 0xa2, 0xa4, 0xa8, 0x28, 0x85, 0x12, 0x38, 0x12, 0xe9, 0x8a, 0xb8, 0x92,
	0x54, 0x56, 0x54, 0x86, 0xbf, 0x7c, 0x80, 0xb3, 0xf3, 0xb7, 0xb2, 0xce, 0xf9, 0x27, 0x91, 0xe2,
	0x7d, 0x18, 0x7e, 0x27, 0x75, 0x29, 0x96, 0xcc, 0x9b, 0x7a, 0xb3, 0xa3, 0x78, 0x8b, 0xf0, 0x0d,
	0x04, 0x97, 0x94, 0x2c, 0xa9, 0x94, 0xcc, 0x9f, 0xf6, 0x66, 0xc7, 0xf3, 0xc7, 0x91, 0x2b, 0x13,
	0x5d, 0x4b, 0x44, 0x1f, 0x6d, 0xdf, 0x87, 0x5c, 0x95, 0x75, 0xdc, 0x4c, 0x21, 0x83, 0x20, 0xe1,
	0x5c, 0x6c, 0x72, 0xc5, 0x7a, 0x46, 0xb9, 0x81, 0xf8, 0x00, 0x8e, 0xb8, 0xc8, 0x55, 0x92, 0xe5,
	0x54, 0xb2, 0xbe, 0xa9, 0x5d, 0x13, 0xda, 0x90, 0x5d, 0xc4, 0x06, 0xd6, 0x90, 0x45, 0x9a, 0x5f,
	0x52, 0x95, 0x71, 0x62, 0x43, 0xcb, 0x5b, 0xa4, 0xf9, 0x42, 0xac, 0x33, 0x5e, 0xb3, 0x60, 0xea,
	0xcd, 0x06, 0xf1, 0x16, 0x4d, 0x4e, 0x61, 0xe4, 0x1a, 0xc3, 0x31, 0xf4, 0xae, 0xa8, 0xde, 0x5e,
	0xa9, 0x7f, 0xe2, 0x3d, 0x18, 0x54, 0xc9, 0x7a, 0x43, 0xcc, 0x37, 0x9c, 0x05, 0xa7, 0xfe, 0x4b,
	0x2f, 0xfc, 0xe9, 0xc1, 0xf8, 0x73, 0x26, 0x55, 0x73, 0xa2, 0xfc, 0x22, 0x2f, 0x1c, 0x03, 0xde,
	0x0e, 0x03, 0xbe, 0x6b, 0x00, 0x4f, 0x00, 0x8a, 0xe4, 0x22, 0xcb, 0x13, 0x95, 0x89, 0xdc, 0x64,
	0x30, 0x88, 0x1d, 0x06, 0x5f, 0xc0, 0x61, 0x21, 0x64, 0x66, 0xaa, 0x3a, 0x85, 0xe3, 0x39, 0xdb,
	0x15, 0x71, 0xfc, 0xa7, 0x33, 0x7c, 0x07, 0xd8, 0x72, 0x16, 0x53, 0xb1, 0xae, 0xf1, 0x29, 0xf4,
	0x57, 0x22, 0x95, 0xcc, 0x33, 0x7f, 0xd5, 0x6e, 0x1d, 0xd3, 0x15, 0xbe, 0x82, 0x3b, 0x8b, 0xa4,
	0xa2, 0x86, 0xd5, 0xc7, 0x3d, 0x81, 0xde, 0x4a, 0xa4, 0xe6, 0xb2, 0x7d, 0xf3, 0xba, 0x29, 0x7c,
	0x06, 0x77, 0xdd, 0x71, 0xeb, 0x80, 0x41, 0x20, 0x37, 0x9c, 0x93, 0x94, 0x46, 0xe4, 0x30, 0x6e,
	0x60, 0xf8, 0x1a, 0xc6, 0xef, 0xd7, 0x94, 0xe4, 0xff, 0x58, 0xd7, 0xbf, 0xc9, 0xba, 0x08, 0xb0,
	0x35, 0xff, 0x9f, 0x7d, 0xf3, 0x1f, 0x3e, 0x04, 0x67, 0xe7, 0x0b, 0xfd, 0x00, 0xf0, 0x2b, 0x8c,
	0x5c, 0xab, 0xf8, 0xb0, 0xbd, 0xaa, 0x93, 0xc2, 0xe4, 0xd1, 0xee, 0xb2, 0xd9, 0x1a, 0x1e, 0xe0,
	0x02, 0x6e, 0xb5, 0xf2, 0xc7, 0x93, 0xf6, 0x4c, 0xf7, 0xb3, 0x99, 0x4c, 0xf7, 0xd4, 0x1d, 0xd1,
	0xd6, 0x89, 0x5d, 0xd1, 0x6e, 0x7e, 0x5d, 0xd1, 0xbf, 0xf3, 0x09, 0x0f, 0xd2, 0xa1, 0x79, 0xfd,
	0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xf7, 0x1f, 0x75, 0x0f, 0x04, 0x00, 0x00,
}
